### ISSUE TITLE
v0.2.0

### ISSUE THREAD

**Issue by egavazzi** [egavazzi/AURORA.jl#5]
What's new:

- [x] the input from file function now handles non-matching time arrays #6 
- [x] performance improvements #12 
- [x] partial rewrite of the setup in Julia #8
- [x] the MATLAB scripts that AURORA.jl still depends on are now directly packaged with AURORA.jl #10 
- [x] add a proper citation file
- [x] code is renamed to AURORA.jl
- [x] a bug with the beam weights and Pmu2mup matrices is fixed #7
